name = input("enter the name of student = ")
age = int(input("enter the age of student = "))
standard = int(input("enter the class of student = "))
print("name = ",name , "   age = ",age,"  class =",standard)
print('\n')
print("name = ",name)
print(" age = ",age)
print(" class =",standard)
